### ISSUE TITLE
Warrior class

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#113]
The __Warrior__ class will be available soon in-game, so we need to finish, improve and tweak some last things...

#### Gameplay informations
A player becomes a Warrior only if (s)he's wearing a **full** mithril (or better) armor. This gives access to specific perks (and downsides):
- Ability to wield the more powerful swords of the game : __Mithril Sword__ and __Dungeon Master's Blood Sword__
- Can wear mithril shields or better (the default Adventurer class can wear shields until diamond shield), which regenerate health over time
- Can craft the __Dungeon Master's Blood Sword__. The Warrior needs to kill the _Dungeon Masters_ for its __Dungeon Master's Blood__ and needs also to kill _Zombies_ in the _Nether Forest_ to get __Zombie Tibia__.
- One of the greatest hunger exhausting coefficient

#### To Do List
- [x] Dungeon Master's Blood Sword texture
- [x] Dungeon Master's Blood Sword caracteristics
- [x] Dungeon Master's Blood texture https://github.com/Ombridride/minetest-minetestforfun-server/commit/ad52d736bbd666c84eb7e6e33bd8cfd7b40a190a
- [x] Dungeon Master's Blood drop implemanted
- [x] For the life regeneration of shields, activate the regen. life of the mod 3d_armor and set it for all to 0, except for Shields (it's a warrior privilege) https://github.com/Ombridride/minetest-minetestforfun-server/commit/bffe0640164f935417a5b2c99b3f3cdc4f0fdaa3 https://github.com/Ombridride/minetest-minetestforfun-server/commit/e94857807f0bce32a2e16134f32d003c6129fa40
- [x] Tweak the life regeneration for Warrior shields
- [X] Sound when the armor is fully equiped => sound choosed, need to put it in pclasses now => https://github.com/Ombridride/minetest-minetestforfun-server/commit/7fe84434cf41a41cc9f820dc1dba89c2e309dd06
- [x] Warrior Mithril armor texture
- [x] Warrior Mithril armor caracteristics + implementation
- [x] Warrior Black Mithril Plated armor caracteristics (a little better than the Mithril shield) @Ombridride
- [x] Warrior Black Mithril Shield texture https://github.com/Ombridride/minetest-minetestforfun-server/commit/3bf43857a3b549d0014fed4a4577be7cb38f6ac0
- [x] Warrior Black Mithril Plated armor texture https://github.com/Ombridride/minetest-minetestforfun-server/commit/e0bc44a4f756ac29eb3fc44f67d0f9b158b8e4ae
- [x] Warrior Black Mithril Plated armor drop implementation https://github.com/Ombridride/minetest-minetestforfun-server/commit/830a7924c98b106ebfbf383b231ad507c1829aaa
- [X] When wearing full armor, become Warrior @LeMagnesium => https://github.com/Ombridride/minetest-minetestforfun-server/commit/0f562cd59e4e1039be2df6cf28ac9d041e7d602d
- [x] Only the Warrior can wear Mithril Sword, DM's Blood Sword, Mithril Armor and the Black Mithril Plated armor @LeMagnesium 
- [x] Check and adjust the life regeneration of the Warrior armors set https://github.com/Ombridride/minetest-minetestforfun-server/commit/b4bf5938741dec2af74fedeec0b6b6922b200799

#### Other information(s)
We need to create the class category for players as soon as possible

**Comment by Ombridride** [comment]
Need to check this thing
@Ataron says :  Je n'avais pas pusher la texture du dungeon master blood ?

**Comment by Ataron** [comment]
Apparently no, then I did : https://github.com/Ombridride/minetest-minetestforfun-server/commit/ad52d736bbd666c84eb7e6e33bd8cfd7b40a190a

**Comment by Ombridride** [comment]
For the most of the latest task, we are waiting @LeMagnesium [pclasses] mod (https://github.com/Ombridride/minetest-minetestforfun-server/commit/117b25bc36fa39b3ecb5005dd0f2990d17648cfe)

**Comment by Ombridride** [comment]
Now ingame, i closed this issue.
For bugfix, this ticket is opened : https://github.com/MinetestForFun/minetest-minetestforfun-server/issues/169
