### ISSUE TITLE
Hunter class

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#114]
The __Hunter__ class will be available soon in-game, so we need to finish, improve and tweak some last things...

#### Gameplay informations
A player becomes a Hunter only if (s)he's wearing a **full** (hardened and next reinforced) leather armor. This gives access to specific perks:
- Ability to use the more powerful Bows and Crossbows of the game 
- Better stamina limit +10 for the first armor set, and +20 for the second
- No hunger exhausting coefficient in his armors

#### To Do List
- [x] Minotaur Horn's Bow texture
- [x] Minotaur Horn's Bow caracteristics https://github.com/Ombridride/minetest-minetestforfun-server/commit/0e9ba218d2640e319888137ddde9aa6f74777838
- [x] Minotaur Horn's texture
- [x] Add a craft recipe, 1* "moreores:mithril_ingot" = 2* "throwing:string_mithril" (into the throwing mod) https://github.com/Ombridride/minetest-minetestforfun-server/commit/0e9ba218d2640e319888137ddde9aa6f74777838
- [x] Add the "throwing:string_mithril" item wich replaced the "farming:string" for the Minotaur Horn Bow Improved https://github.com/Ombridride/minetest-minetestforfun-server/commit/0e9ba218d2640e319888137ddde9aa6f74777838
- [x] Add "throwing:string_mithril" texture (mithril string) https://github.com/Ombridride/minetest-minetestforfun-server/commit/ffc3937f1ec47ca6f6b62521f34b1ecd9d9cd1ed
- [x] Dig arrow bug, when the arrow dig a node, a tool(shovel,pickaxe,etc) are dropped, remove this feature/bug... https://github.com/Ombridride/minetest-minetestforfun-server/commit/3f288ae1840ef5d0d488994fedd5f07a2d095ab6
- [x] Minotaur Horn's drop implemanted
- [x] Desactivate the "infinity arrow", and create arrow per 16 instead of 1 infinite for now...
- [x] Tweak the digs arrows to detect and don't break protected areas + unbreakable nodes
- [x] Removed the tnt_arrow, thank to the mod configuration file
- [x] The fire arrow is too dangerous, we need to disable the fire propagation function, thanks to the mod configuration file
- [x] Re-do all textures in 32px
- [X] Sound when the armor is fully equiped => sound choosed, need to put it in pclasses now => https://github.com/Ombridride/minetest-minetestforfun-server/commit/7fe84434cf41a41cc9f820dc1dba89c2e309dd06
- [x] Hunter Leather armor texture
- [x] Hunter Leather armor caracteristics + implementation
- [x] Hunter Reinforced Leather armor texture
- [x] Hunter Reinforced Leather armor caracteristics + implementation
- [x] Can't wear Shields, if 1 piece or more of the Hunter set is wearing
- [x] If the Hunter armor is fully wearing, the endurance regeneration is faster (hardened = +10 max stamina, reinforced = +20 max stamina) @LeMagnesium 
- [x] Minotaur Horn Bow improved texture https://github.com/Ombridride/minetest-minetestforfun-server/commit/0e9ba218d2640e319888137ddde9aa6f74777838
- [x] Minotaur Horn Bow improved caracteristics https://github.com/Ombridride/minetest-minetestforfun-server/commit/0e9ba218d2640e319888137ddde9aa6f74777838
- [x] Minotaur Horn Bow improved craft https://github.com/Ombridride/minetest-minetestforfun-server/commit/0e9ba218d2640e319888137ddde9aa6f74777838
- [X] When wearing full armor, become Hunter @LeMagnesium => https://github.com/Ombridride/minetest-minetestforfun-server/commit/7305bae805b9018d3d89db3abf838497a3079bf4
- [X] Only the  Hunter can wear Minotaur Horn Bow, Minotaur Horn Bow Improved (so, if Leather armor or the Reinforced Leather armor is wearing) @LeMagnesium => https://github.com/Ombridride/minetest-minetestforfun-server/commit/7fe84434cf41a41cc9f820dc1dba89c2e309dd06
- [x] Create a Mithril arrow, only used by hunter class player, wich inflicts more damage(s) than the diamond arrow https://github.com/Ombridride/minetest-minetestforfun-server/commit/d058fde11116fdc8c32a2cb9a175e6f8fd9b71a9 https://github.com/Ombridride/minetest-minetestforfun-server/commit/5d1d36b7314f9c0de330b212a1b11177f21079e6
- [x] Removed 1/2(50%) arrows wich hit a node/monster/player ! (actually no removed function when hit something...) https://github.com/Ombridride/minetest-minetestforfun-server/commit/951346643c777817fdc643760f707cbd0a7fd9b2

#### Other information(s)
We need to create the class category for players as soon as possible

**Comment by LeMagnesium** [comment]
https://github.com/Ombridride/minetest-minetestforfun-server/commit/2e1803efe0d314f1ccc6e5a9ec0d7e9ff487468f

**Comment by Ombridride** [comment]
For the most of the latest task, we are waiting @LeMagnesium [pclasses] mod (https://github.com/Ombridride/minetest-minetestforfun-server/commit/117b25bc36fa39b3ecb5005dd0f2990d17648cfe)

**Comment by LeMagnesium** [comment]
PClasses will only be finished when every class will be implemented with their reserved items and attribution functions. Then, we will need to add the triggers for `pclasses.api.assign_class` wherever it's needed and add restrictions for features in other mods.

**Comment by Ombridride** [comment]
Now ingame, i closed this issue.
For bugfix, this ticket is opened : https://github.com/MinetestForFun/minetest-minetestforfun-server/issues/169
