### ISSUE TITLE
create a mod for generate map with forceload (if possible)

### ISSUE THREAD

**Issue by crabman77** [MinetestForFun/minetest-minetestforfun-server#128]
Todo : If possible, using forceload to auto generate map when 0 player connected .

**Comment by gravgun** [comment]
Sadly forceloading a mapblock doesn't trigger its map generation. Another useful feature missing from core! Unless we find a hack/workaround (likely involving a fake player or something), generating mapblocks automatically won't be possible unless the core developers move their asses.

**Comment by Ombridride** [comment]
We need to ask core-devs a way to generate automatically the worldmap, maybe a tool exist ?

**Comment by Ombridride** [comment]
No possible for now, so i closed the issue...

**Comment by Ombridride** [comment]
You need to see this : https://forum.minetest.net/viewtopic.php?f=9&t=12943&view=unread#p185817

**Comment by gravgun** [comment]
@Ombridride Nice try from him but this has even less functionality than rubenwardy's `forceload` script. As I said, there is **no** way to trigger mapgen from the API, so **no** mod will be able to do it until they implement this feature in MT core.

**Comment by Ombridride** [comment]
Yes i understand, but this post was interresting, so i share it here :p
