### ISSUE TITLE
Convert admin stuff into wooden stuff at boot

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#139]
For security issues, the best is to convert admin stuff into wooden stuff at minetestserver boot, the aliases mod/file https://github.com/Ombridride/minetest-minetestforfun-server/blob/5c008ce6f694a3ab9743c1f3e9c97e82384848b3/mods/_misc/aliases.lua specify this thing, but it didn't work...

Admin armor file : https://github.com/Ombridride/minetest-minetestforfun-server/blob/5c008ce6f694a3ab9743c1f3e9c97e82384848b3/mods/3d_armor/3d_armor/admin.lua

**Comment by LeMagnesium** [comment]
Do you want to reconsider an "admin" class with those items reserved for it? It would be a lot easier.

**Comment by gravgun** [comment]
@LeMagnesium I'd consider a privilege rather than a class.

**Comment by LeMagnesium** [comment]
"server" is the admin privilege. It's the trigger of my early implementation of the [admin_class](https://github.com/LeMagnesium/minetest-minetestforfun-server/tree/admin_class).

**Comment by Ombridride** [comment]
I just wanted this items only for admins, we just need to find a way to do that, maybe delete it if you try to wear it without the privilege admin ?

**Comment by Ombridride** [comment]
@LeMagnesium create an admin classe for admin stuff please, it's a very great idea !

**Comment by LeMagnesium** [comment]
It's stashed somewhere in a git branch, I just have to rebase it. Will be pushed soon.

**Comment by LeMagnesium** [comment]
Admin class : https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/d06d4754ef17802efd5a59d9db37677666473e6b
