### ISSUE TITLE
tectonic faults and liquid

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#143]
Sometimes you come into a tectonic fault, and you always get tons of liquid. It can be acid, lava, or water.

It's really too much: generation is very laggy (I saw up to 12 seconds on my computer, playing alone), with the usual disagreements, like "already dead" mobs killing you, drowning out of the water, extremes rollbacks, aso. 

In this case, mining in a fault is a suicide (I lost today 5 diamonds, 25 mese crystals, 400 coals and 250 iron...)

Much more, I saw once a "roof" of water, not flowing anymore, a bit above my head.

My proposal: remove at least 90% of all liquid sources generated in the faults. In that case we should already see sometimes some (** insert the name of your favorite liquid here**), but it would become playable, and drastically shorten the lag.

**Comment by Ombridride** [comment]
We need to remove liquids(water/acid/lava) in fissures

**Comment by Ombridride** [comment]
Hi @Cyberpangolin, can you retry with the new server config and tell me if you still ahve this problem ? 

Thank you in advance

**Comment by Cyberpangolin** [comment]
I won't have time today, but tomorrow ;)

**Comment by farfadet46** [comment]
it's always open here ? :p

**Comment by Ombridride** [comment]
Closed, the server doesn't "ram" anymore for this kind of things.

If you see any slow down of your minetest, it's your computer/client side now ;)
