### ISSUE TITLE
Invisible, unbreakable nodes: default:mg_cherry_sapling

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/minetest-minetestforfun-server#152]
I found two of them in my area. At (3837, 27, 3504) and (3822, 26, 3490). They are surrounded by ladders and a candle. The invisible node is the mapgen cherry sapling. All the other cherry trees in the area are saplings I planted from cherry trees I found elsewhere. 

The cherry tree was correctly generated on this map before. It may be that their growing function is not triggered anymore at the map generation. 

An other player reported an invisible node too (farfadet46 ?).

Edit:
I checked the cherry tree generation in singleplayer:
I got a log "1 trees grown after 0.08s". I set a worldedit region roughly 25 blocks around the cherry tree I could see and looked for "default:mg_cherry_sapling" in the area. Worldedit found 3 of them !  Only a portion of the default:mg_cherry_sapling nodes are grown to cherry trees at mapgen !

**Comment by mgl512** [comment]
Maybe we could make the node default:mg_cherry_sapling visible (look like the real, non-mapgen sapling), breakable and drop the real default:cherry_sapling. It might be what moretrees does with its mapgen saplings.

**Comment by Ombridride** [comment]
I have see many cheery trees in the new mapgen, if they have really invisible cheery tree it's a problem...

**Comment by mgl512** [comment]
I had the parameter "enable_local_map_saving" set to to  "true" in my minetest.conf. I copied the file map.sqllite from MFF in a local singleplayer game. I did this worldedit thing on my area of 128x128x128: 
//fixedpos set1 3790 -48 3442
//fixedpos set2 3918 80 3570
//replace mg_cherry_sapling cherry_sapling
==> 40 nodes found

I have 40 invisible, unbreakable mg_cherry_saplings on the surface of my area on the server. The on_generated event didn't grow any of them. 0 out of 40 !

**Comment by LeMagnesium** [comment]
`default:mg_cherry_sapling` is a special, uncraftable node, aimed at producing cherry trees generated with the map itself. They's placed on the ground and __*supposed*__ to be replaced just after the map generation. But it's not always the case, which is abnormal.

**Comment by mgl512** [comment]
I did a commit (8d455da4) to make this mg_cherry_sapling visible and breakable, and drop a real cherry_sapling. Evgeryone should now be able to fix this issue without admin privileges on MFF.

**Comment by Ombridride** [comment]
Maybe create a alias for fix existing invisible **mg_cherry_sapling** ?

**Comment by mgl512** [comment]
I don't know for the alias, it may be active on mapgen too and prevent the cherry forests to be created in new areas in the future if the mapgen generation works again. The mapgen generation needs a mg_cherry_sapling to create a tree, it won't work on a real cherry_sapling.

**Comment by mgl512** [comment]
Another solution is to temporarily make the growing ABM that runs on the default:cherry_sapling work on the default:mg_cherry_sapling too. No player would have anything to do to the existing mg_cherry_sapling nodes then, they would eventually become trees by themselves. Until we can figure out what's wrong with the mapgen growing function.

**Comment by Ombridride** [comment]
So, what's the solution ? :/

**Comment by LeMagnesium** [comment]
I extended the ABM, that's the best solution I can see.
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/aa938b0699cbb4383555f1651908a346bef60f0f
