### ISSUE TITLE
Tomato Soup doesn't restore hunger

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#153]
Initial talk from farfadet46 : 
- "La soupe de tomate est trop dure à faire et on perd les bols :/"
- "et elle ne nourrit même pas"
- "nom de l'objet : tomato Soup"

Need to check / fix this annoying Soup ! :)

**Comment by mgl512** [comment]
J'en faisais il y a des mois et ça marchait. Ça a dû être perdu avec le passage de hunger de Hud à Hudbars. La soupe est dans le mod Food. Et c'est vrai que ça ne me plaisait pas non plus de perdre le bol en clay. Il y a d'autres soupes sur le même modèle il me semble, qui devraient ne plus marcher non plus donc.

**Comment by Ombridride** [comment]
JAPP report us it's the same thing for foods based on __farming:orange__

**Comment by LeMagnesium** [comment]
It seems to be an incompatibility between food and hbhunger, both are trying to handle the `item_eat` for both `food:soup_tomato` and `food:orange_juice`.

**Comment by LeMagnesium** [comment]
It seems to be an incompatibility between food and hbhunger, both are trying to handle the `item_eat` for both `food:soup_tomato` and `food:orange_juice`.
EDIT: No, a bug in the subcontracting of `food.item_eat` by `hbhunger.item_eat`. Fixed.
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/793aac3a3a5475503fa5fa9e2632040c9a3ba1fc
