### ISSUE TITLE
Dig_arrow crash

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#157]
![dig_arrow_crash](http://i.imgur.com/NXzEEzA.png)

http://zerobin.qbuissondebon.info/?779a8dc17886e4ea#rzF1d5OWK/1pKyxWIZ+rtWi24vEZMkEqPchcrZMgH7o=

**Comment by crabman77** [comment]
j'abandonne le debug de ce mod, il m'a spawn un uknown  quand j'ai tiré une flèche alors que juste après la flèche est partie comme il faut.
plus tard j'ai tiré quand j'étais en l'air, la flèche part comme il faut puis elle tombe avec un item unknown, en clair elle a décrocher un block d'air ou ignore.
![screenshot_20150727_023202](https://cloud.githubusercontent.com/assets/7189389/8896823/03045972-3408-11e5-8a7c-65b7b700349b.png)

**Comment by Ombridride** [comment]
I closed the issue
The dig arrow is now fixed, crabman has commited something about this...
