### ISSUE TITLE
Bow's damage

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#166]
Actually every bow has exactly the same effect. The only difference is their durability.

![tableau-throwing](https://cloud.githubusercontent.com/assets/12512762/8917554/ebd475f6-34b2-11e5-9091-0646be8410a8.png)

I'm sure we could change that: try to kill a minotaur with 90 arrows (or more: their are very hard to kill with a so good armory)! :/
My proposal:
![capture du 2015-07-27 23 13 44](https://cloud.githubusercontent.com/assets/12512762/8917898/39144c54-34b5-11e5-8b06-620aba31e0f5.png)

Note: I imagine that a mese bow could "charge" with mesecons energy and so be the most powerful. Then you have a strategic choice: do you prefer a better damage value or a faster bow?

+ there could be some bonus for hunter and the wizard (every arrow could double its power but spend 10 of mana?)

**Comment by Ombridride** [comment]
This screenshot is obsolete since a VERY long time, we just need to update the spreadsheet weapons section, you will understand the new very interresting values :)

**Comment by Cyberpangolin** [comment]
okay, sorry then :P I was sure it was forgotten due to the tons of work you have :)

**Comment by Ombridride** [comment]
Now updated and in-game values http://minetestforfun.com/le-jeu/liste-des-mod
