### ISSUE TITLE
Picking up boat destroys it

### ISSUE THREAD

**Issue by mgl512** [MinetestForFun/minetest-minetestforfun-server#167]
Sneak + left click on your boat destroys it instead of picking it up. Punching it destroys it too. But if you have a stack of boats instead of a single one, then everything changes : sneak + left click picks up the one you placed and adds it to your stack. It's not destroyed. Punching it does the same thing. I tried the boat on river water and I'm using commit f593baf8.

Carts work.

**Comment by LeMagnesium** [comment]
This perfectly works, when I sneak + right click on a boat with a bare hand it just adds the boat to any stack available or in the first empty inventory slot. If nobody else can reproduce this bug then try explaining in which conditions you did it (creative, etc..).

**Comment by Ombridride** [comment]
Maybe cause by a lag and the boat was in your inventory long atime after the sneak+click operation ?

I closed because i've tested it and it works.
