### ISSUE TITLE
Integrate [awards] with [unified_inventory]

### ISSUE THREAD

**Issue by gravgun** [MinetestForFun/minetest-minetestforfun-server#168]
Clicking on the newly-introduced awards/achievements button in the inventory shows another formspec instead of showing the list integrated in `unified_inventory`, thus breaking UX continuity with other existing buttons (except the fishing scoreboard).
The `awards` GUI should be shown in the inventory UI itself.
Should be fairly easy to implement.

**Comment by Ombridride** [comment]
I can add something with this issue about awards mod, we need to add the "reward"  after the description of the award, it's more interresting for give players interrest avout succeed awards

**Comment by gravgun** [comment]
e48e76bffcebe2b7781f824c162453c1971b8576 removed `awards` since we plan to progressively replace them with quests. Closing.
