### ISSUE TITLE
Last merge Bugfixs needed

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#169]
#### Last merge Bugfixs needed

- [X] Bugs affect all shields: the preview/inv size is OK, but the wielded preveiw is either 2x too small (if new texture armor(32px), either too big x2 bigger with an old armor set) => tested righ now @Ombridride => https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/6142ca84c46eb2f05918abe7774bcdf21ec212fe
- [X] The blackmithril shield doesn't exist ingame ?! => ~~None was never coded (Mg)~~ => https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/3fd2d1bbf4c02c1646c25d108ffc4dbee2797d9a
- [x] Throwing bug, when we throw an arrow and when the arrow touch an entity, it's immediatly transformed into stick and DON'T do any damages, also many crashs of this mod... https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/f1018dfaaf41854eb953011c3312edace9753af3
- [x] Decreased the life regeneration of the warriors armor (too high for now) https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/9ca3ac9383b8e596ad9ccd6b2abcff9d62aa5acb
- [X] The max stamina isn't improved when we are hunter (both armors) => Because you are in admin class => Now debugged https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/d491015a782f9326a844354734f9fe94f5c0406f
- [x] Can't check the blackmithril texture because this shield isn't ingame => Now in-game, pclasses missed lines
- [x] The bobber of the fishing mod is too deep and hard to click sometimes https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/06e0aab31ff82fd815da72f73706cf9ed96b87da
- [X] Weapons fly to far away when you try to pick up one and you're not a warrior/hunter ! => It's not a bug it's a feature. (Mg) => tweaked https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/a4798a030877240fe0ff19df142b1331e89f7f00

**Comment by Ombridride** [comment]
```
- [X] Weapons fly to far away when you try to pick up one and you're not a warrior/hunter ! => **It's not a bug it's a feature.** (Mg)
```

Tweak it, Weapons/armors DOESN'T need to bump/fly 10 nodes away, 2/3/4 nodes is enough.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/a4798a030877240fe0ff19df142b1331e89f7f00

**Comment by crabman77** [comment]
boober fixed https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/06e0aab31ff82fd815da72f73706cf9ed96b87da

" L'appât pour poisson marche ? (Je n'ai pas réussit)"
oui il fonctionnent, c'est un mod un peut plus réaliste, pas une boucle qui fait mordre parce que x-1 fini par faire x==0 :)

**Comment by crabman77** [comment]
fixed more throwing bug https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/f1018dfaaf41854eb953011c3312edace9753af3

**Comment by Ombridride** [comment]
Everything is fixed (normally), i closed the issue.
