### ISSUE TITLE
new weapons (by class) are flying away and disappearing

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#171]
We suppose you have no class: Take a mithril or a DM sword from a chest. It simply disappears. definitely.

drop one of them on the floor and walk near it:
it comes to you starts flying away, you may play football with it (trololo!).

I think we should be able to take them as usual objects, but they should be "useless" as wooden weapons when we are not in the good class. OR: trying using it without the class simply drops it.

**Comment by crabman77** [comment]
It's very bad, if my chestplate break then i lost my sword?, I can't recraft a chesplate in fight with mobs :)

**Comment by LeMagnesium** [comment]
> It's very bad, if my chestplate break then i lost my sword?, I can't recraft a chesplate in fight with mobs :)

That's the point... I could add a delay to drop the item but it's not secure enough for classes like admin..

**Comment by Ombridride** [comment]
With the graveyard, this will not happenned since the next merged, the velocity has been decreased, and now with th graveyard inventory, you will keep your latest other classes items on your graveyard bag ! :)
