### ISSUE TITLE
wishlist: add a bait for mobs

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#172]
Maybe we could add some kind of thing that the evil mobs really like, as a bait, to distract them from the player during some time. I was thinking about a Doll or use homedecor's TV. Of course, that would have a limited amount of time (then the mob destroys the objects), and the mob could still come back to you if you hit it.

Then you can continue mining, or go away... like a chicken, beause you REALLY want to come back to the surface with your new buldozer-only sword that you have mined.

**Comment by farfadet46** [comment]
i like your idea about the TV :D

**Comment by ObaniGemini** [comment]
Animals attracted by TV... Nice :D

**Comment by farfadet46** [comment]
or drop a book XD

**Comment by Ombridride** [comment]
We Will not add this feature, this is a too easy way to kill monsters without difficulty.

If you need a bait, go kill monsters with a Warrior :) (the warrior is a bait, in a way, it's a tank :p)
