### ISSUE TITLE
Quest-reinit time indicator

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#173]
I aborted my 3 quests yesterday evening. They are "failed". It seems that I have to wait for 50'000 seconds. It could be better (more professional) to say 13.9 hours, and if less than an hour, say it in minuts, because 50000 seconds doesn't really make sense...

Another thing: it doesn't refresh, so you could think that the timer is stopped when you see how much time is left. It should refresh regularly

**Comment by Ombridride** [comment]
It's a temporary value and it's easily tweakable, just wait the quest mod first __complete__ stable version !

Just wait or follow the quest mod issue https://github.com/MinetestForFun/minetest-minetestforfun-server/issues/145

**Comment by gravgun** [comment]
@Ombridride The `quests` fork **is** supposed to be stable. Stable doesn't mean complete. The #145 todo list is now complete about the things I wanted to work on, and you'll notice I nowhere made mention of this missing feature. The remaining tasks in it are related to `mff_quests`, not `quests` core. Letting this issue open would be a good idea.

**Comment by Ombridride** [comment]
You can comment without Reopened the issue Gravgun, i think this issue can be closed because you already planned this feature...

**Comment by gravgun** [comment]
@Ombridride I did *think* about it, but did *not plan* it.
