### ISSUE TITLE
Invalid texture in wardrobe

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#175]
if you want change your skin at the wardrobe, the texture is absent and minetest make a dumy texture.

![capture](https://cloud.githubusercontent.com/assets/11613522/8938091/c8ef5c72-355c-11e5-95d7-0578c63acf2d.png)

**Comment by Ombridride** [comment]
have you try ti disconnect/reconnect ?
Your skin is forced to be refresh at your connection, for in-game, it's a 120sec timer if i remember right the value, so you need to wait 2 minutes ingame if you want to show your new skin

**Comment by farfadet46** [comment]
oh ok i need to try :)

**Comment by farfadet46** [comment]
ok can you explain me the error in the console ?
i have many error before i start the game it's the same error ?
All PNG error became before the game start.

![capture](https://cloud.githubusercontent.com/assets/11613522/8939722/6d4aea62-3566-11e5-9d10-cb3532978d3d.PNG)

**Comment by LeMagnesium** [comment]
> All PNG error became before the game start.

Except for the two "ERROR" at the end, the rest is perfectly normal (I had that on my Windows client too). Is there only one texture missing, or are they all missing?

**Comment by LeMagnesium** [comment]
The wardrobe was modified a lot during the last updates of homedecor. It works now. If anything is wrong with the wardrobe, please reopen this issue.
