### ISSUE TITLE
there are 2 cobblestone stairs

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#176]
One written "Cobblestone Stairs"
and one written "Cobblestone Stair"

**Comment by Ombridride** [comment]
"Cobblestone Stair" => __Stairs__ mod
"Cobblestone Stair" => __moreblocks__ mod, created with "circul_saw"

It's the same node, just come from different mods.

We will check if we can do something ;)

**Comment by farfadet46** [comment]
ok because i can't stack them :(

**Comment by LeMagnesium** [comment]
This is not a bug, these are two different stairs. Though, we can maybe add an alias.

**Comment by Ombridride** [comment]
Aliases to from circul_saw stairs to the stairs from the [stairs] mod would be indeed a great idea

**Comment by gravgun** [comment]
@LeMagnesium @Ombridride Aliases are a solution, to the only condition that **both stairs use exactly the same param1 and param2 meanings**. Having different bindings for those attributes would result in a data clash, causing some kind of corruption (e.g. bad rotation).

**Comment by LeMagnesium** [comment]
I saw aliases for slabs in moreblocks but not for stairs, I think it's in fact because we cannot have aliases because of metadata. So, just get used to have multiple type of any stairs made of any material that can be sawn using the circular saw. There is nothing to be done here.
