### ISSUE TITLE
An unknown objet in "coffee table" craft

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#177]
take a look ;)

![sans titre](https://cloud.githubusercontent.com/assets/11613522/8942516/1e9b101c-3576-11e5-918e-2f076c760aca.png)

**Comment by gravgun** [comment]
Actually there's a pretty significant number of crafting recipes involving unknown items. We should list them all here I think.

**Comment by Ombridride** [comment]
Yes @gravgun.

Like @crabman77 does the last time, we just need add a "if xxx mod not activated then remove this craft recipe" near the craft recipes of many items... (mod not activated = mod of the unknow nodes in he screen)

It's not a difficult work, but it's annoying and maybe takes a long time...

**Comment by crabman77** [comment]
There is no "group:wood_slab"

**Comment by Ombridride** [comment]
The issue https://github.com/MinetestForFun/minetest-minetestforfun-server/issues/186 will fix this issue.

**Comment by ObaniGemini** [comment]
Horn_bow improved : does mithril string exit ?

**Comment by Ombridride** [comment]
Yes, string + mithril ingot, and the texture is here ;)

**Comment by LeMagnesium** [comment]
Tables' craft fixed here https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/a97c0e6687589547055f59f422229acc12a7623a .

About the craft recipe shown above, the item `throwing:string_mithril` does simply not exist. The craft recipe was created, but not the item. So I created it. https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/bf7a9b02be0469b615d2c53e74b60ddd565cfc30

If nothing else is needed I think we should close this, and reopen a specific issue dedicated to all craft recipes involving unknown items.

**Comment by Ombridride** [comment]
In your commit you just removed crafts recipes, is it normal ?

**Comment by farfadet46** [comment]
i just found the homedecor:rug_persian and the homedecor:rug_small have unknown objet in it recipe.

**Comment by LeMagnesium** [comment]
Should we open a new issue for all the recipes with unknown items or should we just report the here?
If you report them here, please give both the name of the output item, and the name(s) of the unknown item(s).
@farfadet46 : I already took care of `homedecor:rug_small` , and I dealt with `homedecor:rug_persian`.
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/75d8fb5479dc3f06ea66fd39e172980016cefb23

**Comment by Ombridride** [comment]
@Mg => I prefer this solution, commented the craft recipe we can't use

We should close this issue and ask @farfadet46 to open new issue when he found other unknow nodes, it's a better solution for a "one time traitment"

**Comment by farfadet46** [comment]
ok i agree

**Comment by Ombridride** [comment]
Ok, if you agreed i closed this issue :)

See you soon for another unknow nodes :D
