### ISSUE TITLE
Let's cook some wood!

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#181]
what if we cooked wood trunks to get charcoal in the furnace?

After discussion with MFF, 1 trunk cooked could give us 2 coal units. This would unlock tons of new possibilities with a wood factory :)

**Comment by farfadet46** [comment]
you already can automatize the oil ? why do you want charcoal ? i need more explain :)

**Comment by Ombridride** [comment]
@Cyberpangolin wants automatic default:torch

**Comment by LeMagnesium** [comment]
> what if we cooked wood trunks to get charcoal in the furnace?

No, no, and no. Charcoal was a feature removed in the early moments of Minetest Game by celeron55 to avoid the game to be too easy. We are **NOT** doing the same mistake by adding that in game. If you want torches, dig into the ground with a pickaxe and hope for coal to be close to you.

**Comment by gravgun** [comment]
@LeMagnesium Or, be a wizard and use the to-come-in-the-quite-far-future alchemy :)

**Comment by Ombridride** [comment]
+1 for the @gravgun idea, alchemy for wizard wich use mana will prevent the aotomatic task like this !

**Comment by gravgun** [comment]
@Ombridride Prevent, or encourage automation, in some ways (that will be determined when the time comes). Else we'd have things like pneumatic tubes for no reason ;)

**Comment by Ombridride** [comment]
Yes i again agree with your point of view@gravgun

**Comment by Cyberpangolin** [comment]
I think that if we have mesecons and pipeworks, we should have a way to get coal form them. I don't say it should be efficient :P and I don't think it breaks the gameplay or makes it too easy.
If you need tons of wood to get a small amount of charcoal, you need to cut the wood. And for that, if you want to automatise, you need tons on mese(cons), which means you have mined a lot.

**Comment by Cyberpangolin** [comment]
After reflection, it'sure it should be innefficient.
So my new proposal is: burn 1 trunk, you get 2 or 3 black dye
Craft 9 black dye together: you get 1 coal.
Wood cooking time: 10-20s
Then it's possible but very slow and innefficient. Getting decent amounts of coal would mean huge spends of mesecons.
 BUT: It means we could automatise torches and probably tons of new things I did not think about. And I like that. :)

**Comment by Ombridride** [comment]
1 coal = 1 black dye actually, if im not wrong

We need to have a conversation with this possible feature...

**Comment by ObaniGemini** [comment]
?? Isn't it 1 coal = 4 dyes @Ombridride ?

**Comment by Ataron** [comment]
Yes i think 4

**Comment by LeMagnesium** [comment]
I'm completly oposed to this feature, as I already state above. If you add it in a class, then only consider adding it when the class is finished. Wizards and their alchemy would be complicated enough to use to balance with the ease charcoal/wooden planks turning to coal would provide, for example.
That feature would probably balance a bit with our hardcore specs but I think it will make the game still too easy.

**Comment by Ombridride** [comment]
After discussion we state to this sentence :

- Adding a too many easy way to gain the coal mineral
- If tree trunks (group) will be the craft recipe of the coal, even if burned with a furnace, it promotes to players the way to dig trees (arggg... our biome :() instead of digging in caves

I closed this issue. Sorry ! But thank you anyway for your feature request :)
