### ISSUE TITLE
Update [compassgps] mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#185]
#### Explanation
https://forum.minetest.net/viewtopic.php?f=11&t=9373&start=100#p185847

#### commits 
https://github.com/Kilarin/compassgps/commits/master

**Comment by LeMagnesium** [comment]
When we were talking about removing mods to lighten as much as possible the repository, @gravgun suggested that nobody really used compassgps, and consequently that it should be removed.

**Comment by Ombridride** [comment]
Since we have the realtime worldmap and it works well, you can remove this mod, not very usefull now.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/7f6d82a4c357930b9c657f3c6d0191da5f5a9792
