### ISSUE TITLE
Update [homedecor_modpack] mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#186]
#### Solve other issues
https://forum.minetest.net/viewtopic.php?f=11&t=12767&view=unread#p185788
Solved the issue https://github.com/MinetestForFun/minetest-minetestforfun-server/issues/177

#### Repository
https://github.com/minetest-technic/unified_inventory

**Comment by LeMagnesium** [comment]
> https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/1d85364834fde829f7910c807210575d95f3ff8c

Tell me that's just an error in copy-pasting and I didn't update the wrong repo.
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/a97c0e6687589547055f59f422229acc12a7623a

**Comment by Ombridride** [comment]
Just check the forum topic, @VanessaE is talking about a tweak of this mod wich exclude craft recipe with unknow nodes made by other mod we don't have

**Comment by Ombridride** [comment]
You just removed craft recipe in your commit ! Be carful what you do !

**Comment by LeMagnesium** [comment]
I only removed the craft recipe with those unknown nodes, what are you talking about?
Here are the 5 craft recipes' problems : 
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/a97c0e6687589547055f59f422229acc12a7623a#diff-f903642914cf4d1d2a32311ea5a99bb1L69
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/a97c0e6687589547055f59f422229acc12a7623a#diff-5b7ae49253fcb9dc5bfee22a916b51b5L126
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/a97c0e6687589547055f59f422229acc12a7623a#diff-b39391e50531f878fafcb395ee3566baL52
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/a97c0e6687589547055f59f422229acc12a7623a#diff-975735b6fc38bfcc2b6b338f9c438a60L96
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/a97c0e6687589547055f59f422229acc12a7623a#diff-b97e72c7977c1b80dd99f387d25b14acL95
