### ISSUE TITLE
Too many boats

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#188]
The sea_modpack include boats and uboots, they are too many, it's a problem.... And it makes the mapgen heavier !

![uboots_spawn_rate_too_high](http://i.imgur.com/auPaOuD.png)

- [ ] Divided per 10 the boats/uboots spawn rate

**Comment by LeMagnesium** [comment]
There is no real 'chance' for them to spawn, not real numerical value, so I tried to understand the algorithm designed to 'roll the dice' when generating map, and tweaked it a bit.
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/d7817ae133feba4f4edee70050d594e976f9cdd7

**Comment by Ombridride** [comment]
I think it's ok like that. We will try in-game.
