### ISSUE TITLE
boats drops

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#190]
The boats drop is totally insame/bugged, we have fixed this a long time ago, what is still here ?! (updated missed ?)

So, the boats drops need to be like that :
- [ ] uboots drop / 4

**Comment by LeMagnesium** [comment]
This system has equiprobability to determine the amount of any item given in uboots' chests. I tried to break it as I could but this is not "divided per 4".
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/ddd99bb4b6644dfada311a00cc23e017418e8f0f

**Comment by Ombridride** [comment]
Yes, sorry for the sentence not very clear. thanks to IRC.
