### ISSUE TITLE
Error Deserialisation from MFF@IRC

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#191]
![sans titre](https://cloud.githubusercontent.com/assets/11613522/9108427/418e297e-3c2e-11e5-870d-496716c457c6.png)

**Comment by Ombridride** [comment]
Ton client Minetest ne peut visiblement pas lire certains caractères affichés...

Malheureusement, je doute que nous puissions faire quelque chose...

**Comment by farfadet46** [comment]
Ombidride: j'utilise cette version minetest-0.4.12-7bbb9b0-win64 c'est quand meme bizare que ça ne le fasse qu'a toi car d'autres joueurs sur IRC ne m'affiche pas ce message.
je vais surveiller ça.

**Comment by LeMagnesium** [comment]
C'est une erreur de client, on ne peut rien y faire. C'est un problème provenant de la build que tu as récupéré, de la manière dont elle a été compilée, ou peut-être de la version d'une librairie.
Au pire, reportez ça sur le repo de Minetest.
