### ISSUE TITLE
Tree grow through the rock

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#192]
i dislike that :(

![sans titre](https://cloud.githubusercontent.com/assets/11613522/9122548/0fa6e0ac-3c8a-11e5-913d-551f31d28d36.png)

**Comment by Ombridride** [comment]
It's a __normal feature__, trees can't break other nodes and it's great like this...

Imagine you build a house somewhere, and a tree growth near your house => half of your house are destroyed.

I closed this issue.

**Comment by farfadet46** [comment]
ok no problem ;)
