### ISSUE TITLE
Some artefact in place of the breathing gauge

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#195]
![capture](https://cloud.githubusercontent.com/assets/11613522/9139872/57dfcfc0-3d2d-11e5-87c7-6ab8b0cc653e.PNG)
![screenshot_20150807_175444](https://cloud.githubusercontent.com/assets/11613522/9139909/8fc1f33c-3d2d-11e5-84b7-91b8c1795d06.png)

and when i dig a coal ore i get some error
![capt](https://cloud.githubusercontent.com/assets/11613522/9140025/5314a258-3d2e-11e5-8da6-e9a9a8e9bc90.png)

maybe because i'm under the 4.13 RC build ?

**Comment by farfadet46** [comment]
i have some more problem i think it come with the 0.4.13
![sans titre](https://cloud.githubusercontent.com/assets/11613522/9154874/95fc8916-3ea3-11e5-888d-4aaaf48a3b3a.png)

**Comment by Ombridride** [comment]
Certainly your Minetest client version/compiled version, never see that or reported that earlier...

**Comment by farfadet46** [comment]
yep i think you can close this ticket :)

**Comment by Ombridride** [comment]
Ok, i closed this issue

Thank you anyway for your issue :)
