### ISSUE TITLE
An unknown objet in "sign:sign_wall_red" craft (and other colors of this sign)

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#199]
An other craft with an unknown item 

![sans titre](https://cloud.githubusercontent.com/assets/11613522/9154907/551aed5a-3ea5-11e5-8dee-dc4384588e2d.png)

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/654d1250b635762c45ef6a98504b594bfa65a822
