### ISSUE TITLE
Too much Source of acid

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#200]
The number of acid source per chunck seem to be a little too hight

I mean when i go to mine a big area i found very often a source of acid and always lost all my stuff not the mineral but my mese picaxe ans my mese showel :/

Other idea, don't generate acid in cave or other stuff because the fow go on you maybe 2 minutes after you generate the map.

PS: sorry for my english ... you know... i'm not an english prof ;)

**Comment by Ombridride** [comment]
- [ ] Divided by 2 the acid sound mapgen spawn

**Comment by Ombridride** [comment]
Don't forgot tu update your finished issue @Gael-de-Sailly ;)

(I do it this time)

**Comment by Gael-de-Sailly** [comment]
69e721c
