### ISSUE TITLE
not acces to the minetest official forum

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#202]
hi, i take a look at the todo list (on framapad) https://lite5.framapad.org/p/r.446ce575dd27b3c3e8a8efb34f28ac2d

and some link are innaccessible, like this one "player animation" (https://forum.minetest.net/viewtopic.php?f=5&t=10324&view=unread&sid=2d8bce6e5c9e34ded808004e64e18ed7) the forum says : "You are not authorised to read this forum."

i think it's not important but maybe it's important... and i like post ticket :p

**Comment by Ombridride** [comment]
The player animation topic was moved, it's why you can't read the post :p (same for me)

I will work on remove this useless TDL and add all of its contents in Github issues

**Comment by farfadet46** [comment]
ok :)

**Comment by Ombridride** [comment]
Closed this issue since We moved defenitly the TDL to Github
