### ISSUE TITLE
Update plantlib/moretrees

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#204]
Be carfull, mods split and renamed ! :/

https://forum.minetest.net/viewtopic.php?f=11&t=4394&view=unread#p186643
https://forum.minetest.net/viewtopic.php?f=11&t=3898&view=unread#p186641

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/335b489dfb0f7a3ccac76c36b42cb955c0d33022

**Comment by Ombridride** [comment]
It seems correct, great job (i was affrid for the eventuel other mods which used the lib...)
