### ISSUE TITLE
Removed the [bone] mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#205]
#### Bugged and useless
- [X] Removed the __bone__ mod => https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/0cde41ff4919f7f11f0ed400aae9485c53583bcb

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/0cde41ff4919f7f11f0ed400aae9485c53583bcb
