### ISSUE TITLE
Besoin de portes de 3 node de haut

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#210]
Est'il possible qu'une ame charitable nous crée des portes de 3 nodes de haut ? avoir des portes de 2 bloc pour un chateau c'est moyen :/

**Comment by farfadet46** [comment]
j'avais déjà tenté de modifier le mod 'doors' actuel mais c'est avec plein de variables dans tous les sens :/ du coup j'ai ouvert un ticket car j'en peut plus XD.

voila mon essai :/ mais le plus gros probleme viens de l'ouverture - fermeture et destruction, car il faut vérifier les 3 nodes enfin bref : 

Merci ;)

![screenshot_20150811_182158](https://cloud.githubusercontent.com/assets/11613522/9203195/f1031c9a-4055-11e5-8b34-b448faafd670.png)

**Comment by LeMagnesium** [comment]
Avoir 2 blocs coordonnées c'est déjà un calvaires à entretenir au niveau du code. 3, ce serait encore plus monstrueux. L'idée avait été proposée de créer une section d'API pour les nodes qui occupent plusieurs emplacements.

**Comment by crabman77** [comment]
j'ai presque fini les portes à 3, mais sur un ancien code :( , il faut que je réadapte sur le nouveau

**Comment by crabman77** [comment]
Dès que j'ai les 3 textures pour l'inventaire je push.
![screenshot_20150812_193344](https://cloud.githubusercontent.com/assets/7189389/9231625/733a1f1e-4129-11e5-98ab-e4396b0d11be.png)

**Comment by Ombridride** [comment]
celle en bois est très bien réussit, par contre celle en cerisier fait bizarre ! :)

**Comment by farfadet46** [comment]
merci :p je vais voir si je peut pas faire un truc dans le genre asiatique avec :)

**Comment by crabman77** [comment]
la porte est là, on vous la pose?  https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/07e6c4ae8893fb2e81bfcfa42897f65818cbdcdf

**Comment by Ombridride** [comment]
N'importe qui de l'area peut les poser :)

Pour les _craft recipe_, je les trouve très bien faite, bravo.
