### ISSUE TITLE
i can break the sandstone slab without tools but not the sandstone bloc

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#211]
![screenshot_20150811_214458](https://cloud.githubusercontent.com/assets/11613522/9208186/6171d7ac-4072-11e5-9691-cc184c0c7cbd.png)

**Comment by LeMagnesium** [comment]
Differences between groups of `default:sandstone` and `stairs:slab_sandstone`. That has always existed within Minetest Game.
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/471eae510d1f1877817a99c7fba1e8ca29dabc7c
