### ISSUE TITLE
Problem with fences

### ISSUE THREAD

**Issue by paly2** [MinetestForFun/minetest-minetestforfun-server#212]
`default:default_fence` apparently has the same recipe than `default:fence_wood`... So you can not have `default:fence_wood`...

**Comment by Ombridride** [comment]
Revmoed a recipe or create an alias is a possibility, but we need to investigate before.

**Comment by LeMagnesium** [comment]
The item `fences:fence_wood` replaces `default:fence_wood` on purpose. There's no bug here. So, why do you need `default:fence_wood` in particular?

**Comment by Ombridride** [comment]
You need to look at the craft inventory ingame Mg, there is two wood fences with two different itemstring

**Comment by LeMagnesium** [comment]
Yep, I saw that. But the problem reported here is that you cannot craft one of them. I can easily make the uncraftable one disappear with an alias, but why would you need specifically a `default:fence_wood` and not the other one? Or maybe I just misunderstood.

**Comment by crabman77** [comment]
in fence mod line1 : "local override_original = false  --change to "true" if you want original and placed fences replaced"

https://github.com/MinetestForFun/minetest-minetestforfun-server/blob/master/mods/fences/init.lua#L689

**Comment by paly2** [comment]
Maybe I was wrong in itemstrings...  
I think it is better to create an alias that override some fences...

**Comment by LeMagnesium** [comment]
@paly2: I would rather add `not_in_creative_inventory` to the `default:fence`. An alias would probably break the ability to not override, and the override itself.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/220c04bfc65bd88671f94d675862fffdaed8d56c
