### ISSUE TITLE
Be able to "create" dirt

### ISSUE THREAD

**Issue by paly2** [MinetestForFun/minetest-minetestforfun-server#215]
I think it would be nice to make "dirt factorys". Maybe by crafting it, or something more original : For example, gravel could turn into dirt if it touch acid (normally this should work, but I have not tested: http://paste.ubuntu.com/12078295/).

**Comment by Ombridride** [comment]
Interresting, it can e a good think, with this kind of thing you can created many dirt blocks and build your own artificial island

**Comment by LeMagnesium** [comment]
The dangerosity of acid makes it a good way to create artificially dirt, but I would prefer another process.
I remember an old `dirt` mod that had some things to do with crafting dirt and extracting stones. I will try to dig into my mod database and find it to check if it could be useful in any way.

**Comment by Ombridride** [comment]
I've an idea.

Actually :
Stone > Gravel > Compressed Gravel

Need to be :
Stone > Gravel > Compressed Gravel > __Dirt__

**Comment by LeMagnesium** [comment]
@Ombridride : Good idea, but there is no compressed gravel at the moment, just compressed cobble, and its recipe is composed of two cobble blocks. Yet, having 4 gravels to do 4 dirt blocks is a good idea.
The following patch should add the right recipe, if we agree on that recipe, then I will apply it :
[Patch](http://zerobin.qbuissondebon.info/?f6bff5618bb3fb61#9hx2o5c5qqG1uQizfYTJE0NBZjYgkVK2D33IZ9FQTe0=)

**Comment by farfadet46** [comment]
ça me fait penser que pour le skyblock il existe un systeme semblable... faire cuire de la terre = cobble 1cobble= 2gravel
1gravel= 2dirt
ou un truc comme ça.
ça me semble correct du coup qu'on n'ai pas le double de ce qu'on avait au départ.

**Comment by Ombridride** [comment]
@LeMagnesium 
Sorry, i fix my earlier post ;) (for nodes name, but the craft i said are right)

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/502a814dd3c6b9f6f0282e1f698c066fc3f88bf0
