### ISSUE TITLE
unknown object in throwing:bow_minotaur_horn_improved recipe

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#217]
![capture](https://cloud.githubusercontent.com/assets/11613522/9282635/0a6ec22c-42ce-11e5-8eaa-7ec0a0e4be8f.PNG)

**Comment by crabman77** [comment]
no problem in local, maybe next merge fix it.

**Comment by Ombridride** [comment]
Yes, will be debug in the next merge
