### ISSUE TITLE
Update [plantlife] mod + mt_game subgame + [moretrees] mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#220]
Because of this https://forum.minetest.net/viewtopic.php?f=11&t=3898&view=unread#p187235

**Comment by LeMagnesium** [comment]
The update : https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/5b4172541b0642982e6fdf66280e47a3af8fc19b

The fixes for my **** up during the update : 
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/d32753ab3dd122c6c731a0866497caf7e6318a65

**Comment by Ombridride** [comment]
We need to re-updated the mods ! (VanessaE update it again)

**Comment by LeMagnesium** [comment]
I think we should wait until everything is done, and then merge the whole things (moretrees and plantlife) at once.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/57aad890949b6d61afdeef97130cd967578cb21b

Good enough?

**Comment by Ombridride** [comment]
We will see with the next merge :)

**Comment by Ombridride** [comment]
Update completed, everything works well.
