### ISSUE TITLE
Tester [Mod] Animated 3d chest [3dchest]

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#221]
https://forum.minetest.net/viewtopic.php?f=9&t=13036

If great, add to the HG because interresting for the gameplay, players can see opened chests by other players

- [X] Tweak this mod because of the formspec, texture, or any other things => https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/7f211b53cc27fef43fdbdae25f333248dd1b0cc5

**Comment by farfadet46** [comment]
je l'ai testé en local, il semble pas mal mais besoin de refaire le formspec

**Comment by LeMagnesium** [comment]
> il y a aussi un petit bug de son lorsque on se place 'sur' le coffre.

Développe s'il te plaît.

**Comment by farfadet46** [comment]
salut, lorsque le joueur est placé juste au dessus du coffre (sans faire de manip particulière, juste sauter sur le coffre) le son de marche (je pense) se joue en boucle.

je pense qu'il s'agit d'un problème de collision
Il me semble que ça fait le même problème avec certaines 'fences'.

**Comment by LeMagnesium** [comment]
> je pense qu'il s'agit d'un problème de collision

Problème de collision de l'engine. Ça le ferait sur n'importe quelle entité avec un bruit de footsteps (et normalement le joueur doit faire des petits sauts en permanence).

**Comment by paly2** [comment]
J'ai aussi testé le mod, j'aime beaucoup !
Un autre petit bug : si un bloc est placé derrière le coffre, le couvercle disparaît dans ce bloc quand on ouvre le coffre...
Peut-être rajouter un test dans le code pour détecter la présence d'un tel bloc (si le bloc est de l'air, le coffre peut être ouvert, sinon, le coffre ne peut pas) ?

Je suis d'accord pour le formspec, il est assez mauvais ; mais il suffit de copier le formspec des coffres de default !

**Comment by farfadet46** [comment]
exact.
pour ce qui est du couvercle du coffre c'est surtout le node au dessus qui "devrais" empêcher le coffre de s'ouvrir. du coup, dans une zone protégée le coffre qui n'est pas locked, peut l’être avec un bloc dessus :)

sinon ce n'est qu'un détail visuel.

**Comment by Ombridride** [comment]
Je pense qu'il faut faire un check : 
Si un bloc est au dessus ou derrière, alors ne pas afficher l'animation. 
C'est seul moyen "propre" que je vois...

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/7f211b53cc27fef43fdbdae25f333248dd1b0cc5

**Comment by LeMagnesium** [comment]
Sorry I forgot we had to test it for Hg.

**Comment by Ombridride** [comment]
Mg, tu agis trop vite sans lire le fil de discussion, nous n'avons pas encoré décidé de la solution à adopter pour ce mod, qui plus est il a pas mal de choses a retoucher, comme le formspec, la texture, et les conditions pour voir l'animation.

Merci de revert ton commit ou alors donne des explications sur ce qui a été fait, et a en voir ton code, il manque des modifications....

**Comment by LeMagnesium** [comment]
> qui plus est il a pas mal de choses a retoucher, comme le formspec, la texture, et les conditions pour voir l'animation.

Oui c'est drôle c'est ce que j'ai fait avant de le push.
J'ai du fixer le formspec, le code a été sorti à l'arrache d'un subgame et il était plutôt mal fait. J'ai aussi du ajouter un can_dig pour éviter de casser le chest avec ce qu'il avait dedans, et j'ai du render l'entité du chest immortelle en cas de bug.
Dans un second temps :

> A ré-écrire car formspec pas bon

J'ai fait ce qui était écrit, si tu souhaites avoir les textures des chests normaux, écrit-le.
Pour le coup de l'animation je le rajoute avec le reste : 
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/195a0822a2ecaf6d96b9065424970037945507be

"Correction du bug d'animation, des images inventaire, wielded et de l'entité. Un 3dchest ne pourra plus être ouvert si les deux nodes derrière lui ne sont pas de l'air"

Et bien sur que je ne suis pas tout le fil de la conversation, puisqu'en principe le premier post devrait contenir toutes les consignes, et que le reste est la plupart du blabla inutile sur ce qui a été fait ou devrait être fait (avant que ça ne soit reporté sur sur le post original).

**Comment by Ombridride** [comment]
Ok, est ce que le coffre est détruit(+son contenu) si touché par un creeper/DM ?

**Comment by LeMagnesium** [comment]
En théorie, oui.
Maintenant, aussi, mais le contenu est dropé comme les chests normaux.
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/7f78ccf906ed027844a17f4247d811eccf310450

**Comment by Ombridride** [comment]
Oui il faut le même fonctionnement que les chests normaux, merci pour le commit

**Comment by ObaniGemini** [comment]
Does this mod work with double chests mod ???

**Comment by Ombridride** [comment]
Le modèle étant un modèle unique en meshe pour le coffre 1x1, non.

**Comment by LeMagnesium** [comment]
@ObaniGemini: C'est pas le but, et c'est pas recommandé. Les doubles chests comme les 3dchests utilisent des tours et des illusions pour nous faire croire que le node est animé, ou que deux chests sont posés. Mais ce n'est pas le cas.
**Le double** chest est en réalité un seul node qui est arrangé pour s'étendre sur deux emplacements. J'ai écrit quelque chose à ce sujet récemment dans une issue, c'est un tour assez malin mais dangereux, car ça empêche, de visu, plein de systèmes, comme pipeworks, de fonctionner sur les deux côtés du chest.
**L'animated 3Dchest** est aussi une illusion. Le node chest est en réalité invisible, et une entité est placée à l'intérieur de lui. La hitbox du 3dchest empêche en théorie le joueur de tuer l'entité, mais à cause de mon fix pour le can_dig, on pouvait tuer l'entité. C'est encore un exemple de cas où un tour de magie part mal.
Je peux toujours signaler au mécanisme d'enclenchement du placement des double chests que les 3dchests sont aussi acceptés dans l'équation, mais ça perdrait tout son sens de faire des 3dchests, et je ne pourrais pas être sûr qu'un chests redevienne un chest et pas un 3dchest et qu'un 3dchest reste un 3dchest et pas un chest quand le coffre double sera divisé en deux (au drop du dig).

**Comment by ObaniGemini** [comment]
@LeMagnesium : Je suis conscient que le double chest est une illusion (comme les doors d'aillleurs, non ? ) mais il faudrait d'abord adapter le mod pour qu'il ait une fonction double chest avant de l'inclure en jeu, non ? Aujourd'hui beaucoup de monde utilise les double chests, il serait donc importants de ne pas oublier cette information

**Comment by LeMagnesium** [comment]
Les doors sont déjà moins des illusions, car il y a vraiment deux nodes. C'est un simple jeu de coordination des rotations, placements et destructions entre les deux.
Je peux ajouter les 3dchests aux blocks qui créent des Double Chests mais on aura pas de double chests animated..

**Comment by ObaniGemini** [comment]
Au pire, envoyez une demande sur le forum au créateur du mod pour qu'il fasse une version avec double chests. Si ça l'intéresse, ça vous épargnera du boulot.

**Comment by LeMagnesium** [comment]
Pourquoi pas, mais je doute que ça l'intéresse. Ça vaut toujours le coup d'essayer.

**Comment by ObaniGemini** [comment]
Ça pourrait toujours l'intéresser de joindre l'utile à l'agréable ^^

**Comment by Ombridride** [comment]
Ok, why not ask this feature to the modder but :
1) Need to translate this issue in __english__ for a better understanding of the modder
2) Post a message on the forum here : https://forum.minetest.net/viewtopic.php?f=9&t=13036&hilit=3dchest
3) i was jsut adding this modder to our repository, that's a good thing, but in futur please __speak english all the time__ :)
