### ISSUE TITLE
saplings not growing + jungle saplings server crash 

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#222]
It's probably related to the recent moretree update #220 .
Normal sapling seems to be inefficient. 20 minutes after planting 14 trees, nothing has grown - except my playing time ;).

I set it under high priority because wood is no longer renewable and is a critical ressource - we don't want devastated lands without any trace of wood like in Tianjin.
I have just now planted a jungle tree, to check if it's common to all trees.

EDIT: it seems that loading a chunk with a jungle sapling kills the server.  Someone should check the logs. It crashed twice when I was approaching my sapling, coming from a fresh-started game.

**Comment by LeMagnesium** [comment]
I recently did an update of moretrees and plantlife_modpack regarding saplings. It may help, or not.
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/57aad890949b6d61afdeef97130cd967578cb21b

**Comment by Cyberpangolin** [comment]
Now I can confirm: the jungle sapling kills the server if you plant it, wait a moment, and come back. I think it's the jungle tree not growing correctly.

@Mg I really hope your correction avoid these crashes.

**Comment by Cyberpangolin** [comment]
With the recent merge: no more crash. :+1: 

Bad thing: saplings are still not growing. Or at least, they grow very slow so you cannot see one grow in 1 hour ingame.

**Comment by ObaniGemini** [comment]
1 hour in-game = 1 hour in the chunk ?

**Comment by crabman77** [comment]
c'est un mauvais merge, le serveur crashait car la fonction prenait en argument la pos, c'est une table enorme a la place (un petit bout ->  http://zerobin.qbuissondebon.info/?c5d14ad69b596a96#lAY+INNu0KYhc1p99km8W8KUNJIDXfJlu2B6i/PU1OA=) , donc crash.
 @Mg le fix si pas de pos.x|y|z ne fait plus crasher mais rien ne pousse du coup car le fonction est toujours avortée. c'est la galère à s'y retrouver dans le commit, il y a trop de mod updaté dans le seul commit.

**Comment by Cyberpangolin** [comment]
@ObaniGemini : yes, mainly.

If it's so complicated, why not come back to the "old" moretrees, that worked fine? What features do we -really- miss?

**Comment by LeMagnesium** [comment]
@crabman77: I don't understand why. The merge seems correct. I only kept a few snippets of code that we added, none of which was touching any growth function nor sapling definition.
I noticed that moretrees' repository has been updated since my last merge, I will update our mod consequently.

**Comment by Ombridride** [comment]
lol ! That was so simple O_o

**Comment by Ombridride** [comment]
Closed because it's fixed, re-oepned this issue if you don't see growing sapling tree ingame after the merge of this night.

**Comment by Cyberpangolin** [comment]
Then I have to re-open it T_T
30 minutes ingame, no tree. B91b confirmed to me he had no tree too.

**Comment by LeMagnesium** [comment]
Apparently, not only `moretrees` was buggy, `biome_lib`'s functions were buggued and returned nil data.

**Comment by Cyberpangolin** [comment]
After discussion on IRC, this bug is probably related to minetest server's version.
All we need is to upgrade the serv to 0.4.13.
As it's now a "stable" release, it may come soon.

**Comment by Ombridride** [comment]
Indeed @Cyberpangolin , that's why i give this issue the label __Minetest 0.4.13-Release__ :)

**Comment by Cyberpangolin** [comment]
Now it grows! =)
