### ISSUE TITLE
last update mobs bug

### ISSUE THREAD

**Issue by crabman77** [MinetestForFun/minetest-minetestforfun-server#223]
- [x] mobs don't follow items, NPC look diamond  but do not walk towards the player.

- [x] staticdata lost.  issue open https://github.com/tenplus1/mobs/issues/30

**Comment by tenplus1** [comment]
Fixed...

**Comment by crabman77** [comment]
Thanks @tenplus1, but there was also another bug
fixed mob don't follow item https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/ef18954a64dd59405cb8f5645df7ba43671d9b4c

**Comment by crabman77** [comment]
I think it's fixed https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/0b6747966fab1102625ac04e7cb4b2b3103bad8d
