### ISSUE TITLE
the mushroom is unknown node

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#225]
![screenshot_20150819_201542](https://cloud.githubusercontent.com/assets/11613522/9364976/39919838-46af-11e5-93b1-e990c2ddca29.png)

**Comment by Ombridride** [comment]
Can you give us the exact itemstring (with F5 output) please ?

**Comment by farfadet46** [comment]
of course :
![sans titre](https://cloud.githubusercontent.com/assets/11613522/9367760/be114738-46bf-11e5-954d-8a126be9c433.png)

**Comment by LeMagnesium** [comment]
I don't know what I can do, honestly. [The aliases are implemented](https://github.com/MinetestForFun/minetest-minetestforfun-server/blob/master/mods/plantlife_modpack/3dmushrooms/init.lua#L52) and they work for me on my local server with the exact same conditions as MFF.

**Comment by crabman77** [comment]
fixed only one forgets https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/5e8399b17b63c1d342db670cc9852430e5aa340d

**Comment by Ombridride** [comment]
So,  we need to merge again the server,  it will solve this unknown node ;)
