### ISSUE TITLE
Pine trunk is an unknown node

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#226]
![screenshot_154783310](https://cloud.githubusercontent.com/assets/11613522/9379634/f2f78f00-472a-11e5-87fb-738357e483be.png)

**Comment by Ombridride** [comment]
The dropped item seems to be OK, but the texture isn't OK

Maybe the next merge will fix this unknow node, thank you for your report :)

**Comment by Ataron** [comment]
I had the same problem but when you break it and take it it's the good texture.

**Comment by LeMagnesium** [comment]
It happened to me, I don't know what is exactly causing that. I think it might be fixed after the next merge, but I'm not sure. The unknown nodes do not have an itemstring, and they drop the correct version of the pine tree.
It will probably be fixed during the next merge.

**Comment by crabman77** [comment]
the unknown Item is "moretrees:pine_trunk", he drop "default:pine_tree".

**Comment by LeMagnesium** [comment]
It was [fixed](https://github.com/MinetestForFun/minetest-minetestforfun-server/blob/master/mods/moretrees/node_defs.lua#L427). Just wait.
(side note : `default:pinetree` [is an alias for](https://github.com/MinetestForFun/minetest-minetestforfun-server/blob/master/minetestforfun_game/mods/default/aliases.lua#L72) `default:pine_tree`.)

**Comment by Ombridride** [comment]
Fixed since the last merge.

Thank you for reporting this.
