### ISSUE TITLE
Nouvelle idée de mod pour la peche

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#227]
Pour avoir plus de chance en pêche il nous faudrait un stuff de pêcheur
genre casque du pêcheur + bottes du pêcheur = rapidité de pêche augmentée de 50% par exemple

**Comment by Ombridride** [comment]
Bonne idée, mais le mod fishing initial n'a pas été prévu pour ce genre de fonctionnalité.
Cependant, c'est faisable :)

**Comment by crabman77** [comment]
pour moi c'est de 1 trop compliqué à mette en place, il faut modifié le système ,donc casser toute la conf, le système qui permet à l'admin de configurer, le système de pourcentage des appâts automatique.

et de 2 on ne va pas mettre un truc qui fouille l'inventaire pour voir si on a tel ou tel équipement, c'est un truc à lag.

en plus après ce n'est plus de la pèche si on s’équipe et on a un poisson a chaque fois sans attendre, comme l'ancien mod enfaite.

**Comment by farfadet46** [comment]
ok you can close this issue :)

**Comment by Ombridride** [comment]
Oui je suis d'accord sur tous tes points @crabman77 
On ferme, fonctionnalitées refusées !
