### ISSUE TITLE
Admin creative inventory

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#228]
The admin armors aren't show in the admin inventory

But, the shield is show... Need to show the other parts of admin armor

**Comment by LeMagnesium** [comment]
Should I hide the shield or show the armor?

**Comment by Ombridride** [comment]
-> Show the armor

**Comment by LeMagnesium** [comment]
Ok, got it.
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/57a5f9296140acf33f19c64f0f11afc20e7a8ee8
