### ISSUE TITLE
Visual mod fishing

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#229]
a little visual problem :)
![screenshot_20150820_202516](https://cloud.githubusercontent.com/assets/11613522/9391861/a6af16c8-4779-11e5-9fe6-f3729f8d0007.png)

maybe inrectifiable

**Comment by LeMagnesium** [comment]
What's the bug?

**Comment by farfadet46** [comment]
the fishing rod in inverted :p

**Comment by crabman77** [comment]
fixed  https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/2c41969e6a7ea7e3c3d143f6bb01e9eee3fce292
