### ISSUE TITLE
interesting ?

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#230]
Player position + cardinal directions (N S E W) on the minimap
https://forum.minetest.net/viewtopic.php?f=4&t=13035&p=187773#p187773

Interresting ? What do you think about this ?

**Comment by Cyberpangolin** [comment]
excellent!

**Comment by farfadet46** [comment]
i have aldready modified my png for that but in "red" not in "white" because if i'm on snow, i can't see anything :)

**Comment by LeMagnesium** [comment]
I think we should use @farfadet46's  version.

**Comment by Ombridride** [comment]
+1 for farfadet version

**Comment by LeMagnesium** [comment]
If you agree then can I push it?

**Comment by Ombridride** [comment]
Yes you can, it's a light and usefull mod

**Comment by LeMagnesium** [comment]
Oops, it's client-side. I can't do anything. Each client has to download the texture and put it in their minetest's `textures` folder...

**Comment by Ombridride** [comment]
damn :(

**Comment by ObaniGemini** [comment]
Wasn't it obvious ? Minetest GPS is part of Minetest Engine !

**Comment by Ombridride** [comment]
@ObaniGemini 
Just think a little and stop comments everything without informations please...
The minetest Core __could have__ implemented a way to overwrite/put a texture on this compass.

**Comment by LeMagnesium** [comment]
> The minetest Core could have implemented a way to overwrite/put a texture on this compass.

They did.
On client-side. With all the rest of the minimap code.
The only permissions a server has it to block the use of it.

**Comment by Ombridride** [comment]
Yes i've read the commit about the server side permission...

So, we can say a feature is missing...

**Comment by LeMagnesium** [comment]
We can't do anything about that. If you want to advise players to download it and install that texture, do it.

**Comment by Ombridride** [comment]
Closed this issue, feature request open in the __minetest__ repository.

**Comment by nanepiwo** [comment]
Servers can specify texture packs server-side (in  .minetest/textures/server), which should work with minimaps.

**Comment by Ombridride** [comment]
We tried this way and it didn't work...

**Comment by nanepiwo** [comment]
Then the issue on minetest/minetest should be a bug, since texture packs should allow overriding default textures.

**Comment by Ombridride** [comment]
yes, that's the conclusion of @rubenwardy here https://github.com/minetest/minetest/issues/3098
