### ISSUE TITLE
unknown bricks-based node

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#233]
how to reproduce:

1) make a brick block
2) cut it in the circular saw, making stairs (or probably any other block from there)
3) place your cutted block somewhere
4) try to break it: You'll get 9 unknown items. These should be bricks, but probably not 9 (if you have 9, then you can make a complete block, so you make it à la Jesus with his breads.)

-> suggestion: breaking bricks blocks should give you back the block you had, and not some bricks that you need to re-craft.

**Comment by LeMagnesium** [comment]
I seriously thought we fixed that problem with [this alias](https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/f03167691402003f643bc10eb227120878686431) (and that typo in the commit message..) but apparently not.

This will fix it for every brick-based cut moreblock : https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/48c4c2431acaf2f36093001cfa04ba80f8132f7a
