### ISSUE TITLE
Some screenshots because our server is sooo beautiful :)

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#235]
![capture du 2015-08-22 23 24 22](https://cloud.githubusercontent.com/assets/12512762/9426086/83b1f7aa-492a-11e5-9d1c-f4f5963a3233.png)
Usine publique / Public factory (157; -187)

![capture du 2015-08-22 23 31 38](https://cloud.githubusercontent.com/assets/12512762/9426091/83b70560-492a-11e5-97f1-2c6e6af61d2f.png)
Pont suspendu / Hanging bridge (160; -136)

![capture du 2015-08-22 23 33 28](https://cloud.githubusercontent.com/assets/12512762/9426089/83b5d2c6-492a-11e5-9239-83ff42a01892.png)
Pont de pierre / Stone bridge (240; -40)

![capture du 2015-08-22 23 35 09](https://cloud.githubusercontent.com/assets/12512762/9426090/83b64dc8-492a-11e5-9c69-d52520ef08ef.png)
Vue de la maison arbre de Mg/ View from Mg's treehouse (250; 20)

![capture du 2015-08-22 23 35 41](https://cloud.githubusercontent.com/assets/12512762/9426088/83b55e22-492a-11e5-9a4f-4ab88a3eab9f.png)
Ile du spawn / Spawn island

![capture du 2015-08-22 23 37 03](https://cloud.githubusercontent.com/assets/12512762/9426087/83b4a41e-492a-11e5-824e-1b8b41cf61a5.png)
Tour du spawn / Spawn tower (30; 0)

![capture du 2015-08-22 23 37 38](https://cloud.githubusercontent.com/assets/12512762/9426092/83ca7d2a-492a-11e5-8128-92e6a8ddb8b3.png)
Château de Paligé / Paligé's castle

![capture du 2015-08-22 23 38 29](https://cloud.githubusercontent.com/assets/12512762/9426094/83cd3970-492a-11e5-8c4e-06950869a30c.png)
Accès au Nether / Nether's access (-40; -20)

![capture du 2015-08-22 23 39 43](https://cloud.githubusercontent.com/assets/12512762/9426093/83ccf7da-492a-11e5-8672-3e8fb8dc8263.png)
Biomes variés / Various biomes

For the website!

**Comment by ObaniGemini** [comment]
Nice :)
Just a few more and it will be all good :D

**Comment by Cyberpangolin** [comment]
Yep, I want to show mobs, npc, player, and so on. but not tonight :P

**Comment by Ombridride** [comment]
Nice adds for banners / galery, thank you cyber ! :)

**Comment by paly2** [comment]
Yeah, screenshots are beautifull !

**Comment by Ombridride** [comment]
Add two new banners :
![new_banner1](http://i.imgur.com/o6Ri2GQ.png)
![new_banner2](http://i.imgur.com/6diNJ5P.png)

**Comment by Ombridride** [comment]
Now, more screenshots in the Galery : http://minetestforfun.com/galerie
and i translated in english this part of the website

!(new_galery)[http://i.imgur.com/F4sssHS.png]

(PS : add a "S" to BiomeS, for the biomes banner)

**Comment by Ombridride** [comment]
Everything is Done, i closed the issue

Thank you @Cyberpangolin !
