### ISSUE TITLE
Quests and nodebreaker

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#236]
1) Build a cobble generator (lava + water + node breaker)
2) Let it run a bit
3) Your quest for cobble digging is done, even if you did not do anything.

suggestion: short-term: stone made from lava could be visually the same as the usual one, act exactly the same, but have another name to make quest forget it.
long-term: node breaker should act as a virtual player (with the name of "node-breaker"?) and not in the name of the player who put it.

**Comment by farfadet46** [comment]
if you create another name, you can't stack it :/
i mean : if i get some cobble from mining i cant stack it with my cobble from the node breaker.

**Comment by Cyberpangolin** [comment]
Good point. I didn't think in the good way. Maybe the quest doesn't care about aliases, so we could trick with it?

**Comment by paly2** [comment]
And if you create another name, there will be lots of problems because the player doesn't exist...
For the moment, the node breaker already uses a virtual player, with the name of its owner.

But I believe that the item get at the end of the quest is dropped... So the player who succeds does not change anything, right ?

**Comment by paly2** [comment]
If you create an alias, the quest will work with the alias and with the "original" item. It's not a solution...

**Comment by LeMagnesium** [comment]
> Your quest for cobble digging is done, even if you did not do anything.

Yup. That's normal, since every wielder (nodebreakers, node placers) simulates the presence of the owner near the block to make the server log the break/place as from the owner. The only thing @gravgun could do about that would be to check the closeness of the player and the dug node.

**Comment by gravgun** [comment]
@LeMagnesium Here goes another core engine flaw: being unable to determine if the dug node was dug directly or remotely...

**Comment by Ombridride** [comment]
That's not a bug, when a nodebreaker dig a node, it's like you dig this node.

The "stone" quests is a very easy quests, you can complet it with this solution if you want.

The others quests can't be done like this.

**Comment by gravgun** [comment]
@Ombridride I didn't say "bug", I said "flaw", which is conceptually similar but different. A bug exists by lack of good implementation, a flaw exists by lack of good design.

**Comment by LeMagnesium** [comment]
Then wouldn't it be possible to check if a player is close to the node they dug before increasing the amount of blocks dug? The maximum range a player can reach is 4 nodes as far as I remember.

**Comment by Ombridride** [comment]
For me this issue just need to be closed, no tweak or fix needed...

**Comment by Ombridride** [comment]
Not a bug, the nodebreaker works like this, that's all.

And this "usebug" is very minor.
