### ISSUE TITLE
"Home" Position is 1 node lower than where it should be

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#237]
The game seems to register a home position 1 node to low. Probably it's related to the way your position is registred and the way you get teleported.

Example: I was on the floor, I registered my home with sethome
then I wanted to come back home.
and here I am.

![capture du 2015-08-24 01 11 12](https://cloud.githubusercontent.com/assets/12512762/9430633/6cb2ea5e-49fd-11e5-9306-c0eae3c13e3e.png)

brick bath ! :D

**Comment by crabman77** [comment]
Fixed https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/645d3afa4892d8fade3951121e7a0e878d1964df

**Comment by Cyberpangolin** [comment]
Thanks. I close and will re-open it if needed.

**Comment by ObaniGemini** [comment]
Thanks, I was falling to each /home ^^

**Comment by Ombridride** [comment]
Great, thank you for this report !

(PS : Don't forget labels/assignee when you closed the issue)
