### ISSUE TITLE
Some Maize node are not animated

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/minetest-minetestforfun-server#238]
![capture du 2015-08-24 13 11 04](https://cloud.githubusercontent.com/assets/12512762/9438895/699b2d62-4a62-11e5-9327-6a7c76573080.png)
Very small maize is animated, and the biggest one too. But not some intermediaries.

Very important. Or not. But it should be investigated once.

**Comment by LeMagnesium** [comment]
That's related to shaders. Maybe the group the `waving_plants` shaders apply to is not set to those maize plants.

**Comment by LeMagnesium** [comment]
In fact it it a field in node definitions that `wapling_plants` use.
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/96c5216e26193b1b45df3c6bf245a799ba58ba55
Now all `waving = 1` are unified. First and second plants won't wave, but third and higher will (only for plants that would wave in real life though).
