### ISSUE TITLE
Disable player punch in the spawn

### ISSUE THREAD

**Issue by LeMagnesium** [MinetestForFun/minetest-minetestforfun-server#240]
- [ ] Add a piece of code to disable damages by punch in the spawn tower (need coordinates)

**Comment by Ombridride** [comment]
Between (16, 0, 12) and (42, 100, -14) for the spawn tower

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/fa9e1e7a1e31487cee303c2f75118ce14a3f47c1
