### ISSUE TITLE
Cobblestone factories produce copper coins

### ISSUE THREAD

**Issue by paly2** [MinetestForFun/minetest-minetestforfun-server#244]
The cobblestone factories (with lava, water and node breaker) produce lots of cobblestone AND some copper coins !

**Comment by farfadet46** [comment]
nice $$ :)

**Comment by LeMagnesium** [comment]
Related to #236
Cobble will sometimes drop copper coin, but you can't tell when it's automated or manually done.

**Comment by Ombridride** [comment]
@LeMagnesium We just need to remove the copper coins dropped by __default:stone__

**Comment by LeMagnesium** [comment]
Why not. Ores still drop coins, right?
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/5c0525d2219ea46659536dbdd026ce3bed19af8c

**Comment by Ombridride** [comment]
yes, that's a nominative drop value.

**Comment by Ombridride** [comment]
So, that's fixed now, closed.
