### ISSUE TITLE
Modelisation de mob

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#247]
On s'attaque a une vache zombie ? XD
![vachezomb](https://cloud.githubusercontent.com/assets/11613522/9541427/43b594c6-4d68-11e5-9c06-e67f1eb60fe1.PNG)

**Comment by Ombridride** [comment]
une vache zombie qui marche xD ?!

**Comment by farfadet46** [comment]
c'est un test mais pourquoi pas XD

**Comment by crabman77** [comment]
Si tu veut t’entraîner, on aura surement besoin d'une tortue à la mario bros.

**Comment by Ombridride** [comment]
En effet bien vu crabman, il faut plusieurs couleurs peut être ?

**Comment by LeMagnesium** [comment]
Une tortue verte, une rouge, et peut-être une bleue.. Ça devrait être assez.

**Comment by crabman77** [comment]
rouge et vert?

**Comment by farfadet46** [comment]
quelques images de référence siouplé :)

**Comment by crabman77** [comment]
dans ce genre http://vignette4.wikia.nocookie.net/mario/images/a/a6/Koopa_Troopa_NSMB.png/revision/latest?cb=20130811201948&path-prefix=fr

**Comment by farfadet46** [comment]
ok mais toujours dans l'esprit cubik ? car cette vilaine est très très ronde XD

**Comment by Ombridride** [comment]
Toujours dans l'esprit cubique oui

**Comment by farfadet46** [comment]
c'est toujours pour un mob animé ?

**Comment by LeMagnesium** [comment]
De préférence oui. Cependant je pense qu'on devrait vraiment faire un repo à part et envoyer le ticket et les modèles dessus. Qu'en dîtes-vous?

**Comment by Ombridride** [comment]
Personnellement je les vois toujours entrain d'être rentré dans leurs coquilles et entrain de tourner

Donc niveau modèle, ça va etre pas trop compliqué

**Comment by Ombridride** [comment]
oui, faut créé un dépot dédié !

**Comment by farfadet46** [comment]
désolé j'ai rien compris avec votre truc de repos :p

![tortue](https://cloud.githubusercontent.com/assets/11613522/9543225/7c786a40-4d77-11e5-9a4a-9c6669bc2411.PNG)

**Comment by Ombridride** [comment]
Moved here : https://github.com/MinetestForFun/minetest-minetestforfun-bros/issues/1
