### ISSUE TITLE
modelisation Tortue

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/minetest-minetestforfun-server#248]
premiere ebauche:
![tortue](https://cloud.githubusercontent.com/assets/11613522/9543193/2ac75d14-4d77-11e5-8397-58d1453b6a4b.PNG)
EDIT: j'ai pas fait de queue c'est grave ? :3

**Comment by Ombridride** [comment]
Moved here : https://github.com/MinetestForFun/minetest-minetestforfun-bros/issues/1
