### ISSUE TITLE
News : bad lisibility

### ISSUE THREAD

**Issue by Gael-de-Sailly** [MinetestForFun/minetest-minetestforfun-server#251]
![News](http://i.imgur.com/pNmaP3v.png)
It seems that the textarea has not the same appearance on every client.

**Comment by LeMagnesium** [comment]
We have no control over the text's color nor the text's size... the only thing we could do is darken the background in the textarea.

**Comment by fabienwang** [comment]
![background](https://cloud.githubusercontent.com/assets/8741873/9563910/73e70f26-4e94-11e5-9032-9733391d794e.jpg)

Would it be nice ?

**Comment by Ataron** [comment]
I think yes

**Comment by LeMagnesium** [comment]
![Better](https://lut.im/OzcrxxDe/bjIKLt47)

Better, but the logo is too low. You should put it a bit upper.

**Comment by LeMagnesium** [comment]
![Good](https://lut.im/Z7ZGT6sq/sTLbzM0u)

**Comment by LeMagnesium** [comment]
Need aproval from @Ombridride .

**Comment by Ombridride** [comment]
That's good for me

**Comment by fabienwang** [comment]
![background](https://cloud.githubusercontent.com/assets/8741873/9564035/ed84c9d2-4e98-11e5-85d4-9890561434e6.jpg)

Try with this one.
