### ISSUE TITLE
nether mod bug: /to_hell freely available to all

### ISSUE THREAD

**Issue by fabienwang** [MinetestForFun/minetest-minetestforfun-server#252]
After a check on register_chatcommand and privilieges checks on the whole repository,
It seems that:

/to_hell doesn't check for any privs
but then it's possible to get stuck there

/from_hell checks for priv "nether" so we can't set ourselves out of Hell.

I think one or another should be fixed, either allow everyone to get there & out
or don't allow any of those command

PS: i'm stuck in Hell xD

<MFF-Bot> fabienwang est mort(e) dans de la lave.
<MFF-Bot> fabienwang pensait que la lave etait cool.
<MFF-Bot> fabienwang ne savait pas que la lave etait vraiment chaude.
<MFF-Bot> fabienwang s'est sentit oblige de toucher la lave.
<MFF-Bot> fabienwang est tombe dans la lave.
<MFF-Bot> fabienwang s'est sentit oblige de toucher la lave.
<MFF-Bot> fabienwang ne savait pas que la lave etait vraiment chaude.
<MFF-Bot> fabienwang est tombe dans la lave.
<MFF-Bot> fabienwang ne savait pas que la lave etait vraiment chaude.
<MFF-Bot> fabienwang a detruit l'anneau de Sauron.
<MFF-Bot> fabienwang a perdu la vie.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/f366bc17fdd18b7e4335a585cd7c27c97c9bf786

**Comment by Ombridride** [comment]
Ces chatcommands sont sensése etre supprimées/commentées depuis longtemps, quelqu'un à du mettre à jour le mod nether en les oubliant, merci d'ajouter **des annotations sur le code !**

Ah, et de **RETIRER** ces chatcommands, come avant ;)

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/fcef6588574b9553408af9efcec3bae969ee0bd9

**Comment by Ombridride** [comment]
Supprimer le code sans mettre d'annotations et tu vas de nouveaux faire une erreur au prochain merge Mg... **IL EST PREFERABLE DE METTRE UNE ANNOTATION**

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/6acb5588938e9272097d004a971c27f6accb9a08
Satisfait?

**Comment by Ombridride** [comment]
C'est une solution, merci ;)

**Comment by HybridDog** [comment]
l thought that the effects of a chatcommand called to_hell are obvious…

**Comment by Ombridride** [comment]
we disabled this command because it was too easy to go in the nether world, in our Classic (survival) server we wants players to build they nether portal to go into the nether world :)
