### ISSUE TITLE
Crafting 2 dirts gives Unknown Item

### ISSUE THREAD

**Issue by fabienwang** [MinetestForFun/minetest-minetestforfun-server#254]
Hey,
I don't know why neither where does this come but i'm sure it's not normal :laughing: 

![crafting_2_dirt_gives_unknown_item](https://cloud.githubusercontent.com/assets/8741873/9565778/d7baddc4-4ee5-11e5-8cd1-55eec84a6bf2.png)

**Comment by Ombridride** [comment]
Need to check the craft recipe... this recipe is normal BUT, the output recipe isn't correct, i didn't know what is the normal output recipe... maybe gravel or sand...

Oh, maybe this craft recipe was a issue of @Cyberpangolin ?

**Comment by LeMagnesium** [comment]
Done.
It was a craft recipe to an entity.
https://github.com/MinetestForFun/fishing/commit/d8777494b31187e8717dc2fa07f40834d3b7084f
