### ISSUE TITLE
New (Improved) [Fishing] Mod

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#51]
Crabman works on a new fishing mod, it's very promising, and certainly the future best fishing mod of Minetest !

We don't have many informations to share for the moment, but Crabman still works on his fishing mod...

So, we will add this fishing mod when it will be over.

(maybe youtube testing videos soon)

**Comment by crabman77** [comment]
Work in progress...
https://github.com/crabman77/fishing/commit/ab67ad83b37d05f1ea0febccb9f3dbdac4384c9c

**Comment by Ombridride** [comment]
Great work !

**Comment by crabman77** [comment]
Fishing mod finished  :)
 https://github.com/crabman77/fishing
![fishing1](https://cloud.githubusercontent.com/assets/7189389/8387110/722b20ca-1c56-11e5-9a75-79c9d6f45e7d.png)

![fishing2](https://cloud.githubusercontent.com/assets/7189389/8387116/79f996e2-1c56-11e5-8209-19268c2d7332.png)

![capture-4](https://cloud.githubusercontent.com/assets/7189389/8387142/899d8414-1c56-11e5-86db-32cf57506af2.png)

![capture-7](https://cloud.githubusercontent.com/assets/7189389/8387150/9961a93e-1c56-11e5-921f-260ed5de7272.png)

**Comment by crabman77** [comment]
Added contest game, demo video  http://youtu.be/8rt8g3F2Gmk

**Comment by Ombridride** [comment]
@crabman77 
Has I understand, your mod is over. Maybe you can replace our actual [fishing] mod with your [fishing] mod (tweaked and improved) now ?

**Comment by crabman77** [comment]
Before We must find the treasure. https://github.com/crabman77/fishing/blob/master/prizes.lua#L40

**Comment by crabman77** [comment]
Fishing merged, but we must find the treasure stuff before  merge on server.
https://github.com/crabman77/fishing/blob/master/prizes.lua#L40

**Comment by Ombridride** [comment]
Now ingame, i closed this issue.
For bugfix, this ticket is opened : https://github.com/MinetestForFun/minetest-minetestforfun-server/issues/169
