### ISSUE TITLE
Avoid Mapgen lags

### ISSUE THREAD

**Issue by Ombridride** [MinetestForFun/minetest-minetestforfun-server#75]
After a discussion with @VanessaE, the better solution for avoid the lag when players generate new chunks in the map is to use a deferred generating (like what plantlife does)

First, we need to list every mod wich generate something in new chuncks :
- Flowers
- Plantlife
- riesenpilz
- nether
- maptools (superapple ?)
- cheery trees
- ...
- ...

And then, we need to search the mod a generating time if it exist already, we can also ask the author of the mod to add it...

Finally, we need to tweak or add a deferred generating time :
- [x] Flowers (default subgame mod)
- [x] Plantlife (everything) => native with plant_lib
- [x] riesenpilz (mushrooms) => no more needed, mapgen changed
- [x] nether trees (forest and normal) => no needed, the nether generation is really fast
- [x] superapple from the maptools mod
- [x] cheery trees (differed time set to 2 second)
- ...
- ...

**Comment by LeMagnesium** [comment]
And what IS a differed generation?

**Comment by VanessaE** [comment]
What you mean is *deferred* generation, where plants_lib merely keeps a log of all blocks generated by the core engine map generator, doing nothing else whatsoever during those events.  During an on-globalstep hook, it plays back the log, splitting each mapblock log entry into a few dozen individual populating steps, checking for total server lag (dtime) before executing each such step.

If the server lag is already above a certain threshold, plants_lib skips what it was about to do and returns control to the server.  By default, this threshold is set to 0.2 seconds, though in practice max server lag ends up being 1 to 2 seconds during active map generation.

**Comment by LeMagnesium** [comment]
@VannessaE, Ok, I get it now. Thanks for the explanation.

**Comment by VanessaE** [comment]
There is.  It's called plants_lib :grin:

**Comment by Ombridride** [comment]
@LeMagnesium @crabman77 @gravgun 
Someone can complete and closef this issue please ? 
I think it's almost over with the new mapgen, i can see the [superapple] mod needs a generation delay and... if you remember another mods wich generate things on the map, feel free to add it and add it a generate delay.

**Comment by Ombridride** [comment]
our mapgen is low enough since the latest server config upgrade, i closed this issue.
